VeriFIT/mata

CMakeLists.txt, include/vata2/convert.hh, include/vata2/nfa.hh, include/vata2/ord_vector.hh, include/vata2/util.hh, src/nfa/nfa-complement.cc, src/nfa/nfa-incl.cc, src/nfa/nfa.cc, src/nfa/tests-nfa-dispatch.cc, src/nfa/tests-nfa.cc, src/tests-vm.cc
This pull request
1. Changes the original data structure for NFA by the data structure developed by Juraj and Lukas.
2. The original data structure for NFA is completely removed - keeping both would need another work which is not now a priority.
3. The new data structure currently is not connected to VM (which is still work in progress), and does not support union_rename and check on disjoints set of states of two automata (which is not supported by our representation). Therefore tests related to these things are turned off".
4. The new data structure is not compatible with the original Pytonh binding. therefore its compilation is turned off.
=> Changing data structures

include/vata2/explicit_lts.hh, include/vata2/nfa.hh, include/vata2/ord_vector.hh, include/vata2/simutil/abstract_transl.hh, include/vata2/simutil/binary_relation.hh, include/vata2/simutil/caching_allocator.hh, include/vata2/simutil/shared_counter.hh, include/vata2/simutil/shared_list.hh, include/vata2/simutil/smart_set.hh, include/vata2/simutil/splitting_relation.hh, include/vata2/simutil/transl_weak.hh, include/vata2/simutil/two_way_dict.hh, include/vata2/simutil/vata.hh, src/CMakeLists.txt, src/explicit_lts_sim.cc, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
This pull request:
-  Imports computation of simulation from the original VATA library
-  Imports the related classes
-  Is based on migration of simulation to the previous library by Juraj.
-  Implements tests for simulation
-  Fixes issues reported by clang-tide and cppcheck
-  Changes names of functions from camel style to snake style
=> Simulation from the original VATA library

include/vata2/nfa.hh, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
This PR implements a method `get_shortest_strings()` for NFAs to get the shortest strings accepted by the NFA.
The PR contains:
1. An implementation of the method `get_shortest_strings()`,
2. Unit tests for the implemented method.
The method is a reimplementation of `get_shortest_strings_bfs()` function from [Python Noodler project](https://github.com/vhavlena/Noodler/blob/d533ee679ceceeae0ed7f9eb1de5a7fd925eaf9c/noodler/algos.py#L58) which computes the shortest strings using a BFS approach which is faster than the [previous approach](https://github.com/vhavlena/Noodler/blob/d533ee679ceceeae0ed7f9eb1de5a7fd925eaf9c/noodler/algos.py#L110).
For the sake of clarity and cleaner code, the method is split into several smaller functions. If we want to keep the method as a single function without …
=> Get shortest strings for NFA

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, include/mata/nfa.hh, src/nfa/nfa.cc, src/nfa/tests-nfa.cc, src/re2parser.cc
Renaming of functions for making states initial and finals + function throw exception when a state is not presented in automaton already. The changes are based on our discussion at yesterday meeting.
=> renaming add initial and final to make initial & final

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, include/mata/nfa.hh, include/mata/ord_vector.hh, src/CMakeLists.txt, src/nfa/nfa.cc, src/nfa/tests-nfa.cc, src/tests-ord-vector.cc
This PR implements functions used in segmentation algorithms. Furthermore, this PR contains implementation of helper functions and generally useful member functions on class (struct) `Mata::Nfa::Nfa`.
All implemented helper functions are required by segmentation algorithms, but are useful for operations on NFAs.
This PR:
1. Fixes `OrdVector` implementation
- Fixes a bug with remove method of `OrdVector`
- Implements intersection method on `OrdVectors`
3. Creates test file for `OrdVector` implementation
7. Reflects changes to methods to make states initial and final
- Accordingly modifies `trans_size()` method
8. Reflects bug fix from Noodler implementation of method to get the shortest words in its Mata implementation 
9. Adds methods to
- Trim redundant states (one of the requested …
=> Implement functions for segmentation

include/mata/nfa.hh, include/mata/noodlify.hh, src/CMakeLists.txt, src/nfa/nfa.cc, src/nfa/noodlify.cc, src/nfa/tests-nfa.cc, src/nfa/tests-noodlify.cc
This PR implements function `noodlify` for noodlification of NFA.
As agreed upon, we implement a naive noodlification method creating all noodles: all permutations of epsilon transitions, one from each depth. In the following PR, we will improve the current implementation with a new algorithm, creating only actually possible noodles which have a path in the original automaton. 
The code has been tested with some tests.
=> Implement noodlification

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/conftest.py, bindings/python/tests/test_nfa.py, bindings/python/tests/test_trans.py, include/mata/nfa.hh, src/nfa/nfa-concatenation.cc, src/nfa/nfa-intersection.cc
This PR extends Python bindings for Mata with bindings for functions from #42.
Each function from #42 has a corresponding binding in Python and at least one test to ensure that the binding works.
I ask for a review from @tfiedor for this draft PR. It would help me if you could go through the code and look for any obvious bugs. I plan to improve documentation in a few places. However, the code should be complete (all tests pass) as it is now. There still might be some implementation changes before opening this PR, but I do not plan anything major, mainly refactorization I hope.
Furthermore, I might add bindings for new `Mata::Nfa::Nfa()` constructors, as discussed in #42.
This PR resolves #42.
=> Add new python bindings

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, include/mata/nfa.hh, src/nfa/nfa-concatenation.cc, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
This PR implements Python binding for simulation minimization from #43.
Seeing as `StateMap<State>` finds plenty of uses, I have introduced a new type in `Mata::Nfa`:
```cpp
using StateToStateMp = StateMap<State>
```
Thanks to this, I can simplify Python binding for a template type `StateMap<State>` to a simple type binding `StateToStateMap`.
I include some tests confirming the binding works as intended.
=> Add Python binding for simulation minimization

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, include/mata/nfa.hh, src/nfa/nfa-incl.cc, src/nfa/nfa-intersection.cc, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
As requested, this PR aims to make alphabet parameter in inclusion and equivalence checks optional.
For this reason, I introduce a new constructor for EnumAlphabet to create ad-hoc alphabet computed from a given automaton (looking at transition symbols of the automaton). The alphabet is then computed for those algorithms (currently only naive inclusion algorithm), which truly require the alphabet and work with it in the algorithm.
Then, when the user gives the functions an already precomputed alphabet, the precomputed alphabet can be used. Otherwise, the following happens: If the alphabet is not necessary, it is not computed at all; if it is necessary, it is computed ad-hoc.
=> Make alphabet parameter optional for inclusion and equivalence checks

include/mata/nfa.hh, src/nfa/nfa.cc
Based on dicussion in issue #33 this PR removes `invert` function and keep `revert` function (with semantics of removed invert function).
Rationalization: `revert` is a standard name in automato libraries and was implemented by Ondra to data structures initally used in this library. The `invert` function was orignally created by Lukas and Juraj in their library for data structures which were later adopted in the Mata library. Therefore we take behaviour of `invert` but keep the name `revert` which is standard.
=> removed invert function

examples/example05-parsing.cc, include/mata/inter-aut.hh, src/inter-aut.cc, src/parser.cc, src/tests-parser.cc
This PR:
- fixes some bugs found during testing on the benchmark provided by Pavol Vargovcik
- adds support for explicit enumeration of initial and final states in cases when they were specified as enumeration. Internally they are still represented as disjunction of states but I added a flag determining that states were originally enumerated and a fucntion for retrieving them as set instead of formula.
=> Bug fixing in parser

include/mata/nfa.hh, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
I have simplified this function and extended its functionality with overloaded function allowing to get epsilon transitions from passed `TransSymbolStates` struct usually used in most algorithms. This new function will be called from within Mata algorithms rather than the function with state as a parameter.
=> Improve getting epsilon transitions

AUTOMATAFORMAT.md, bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, doc/nfa.rst, examples/example05-parsing.cc, include/mata/nfa.hh, include/mata/ord_vector.hh, src/nfa/nfa-complement.cc, src/nfa/nfa-concatenation.cc, src/nfa/nfa-intersection.cc, src/nfa/nfa.cc, src/nfa/noodlify.cc, src/nfa/tests-nfa-concatenation.cc, src/nfa/tests-nfa-intersection.cc, src/nfa/tests-nfa.cc
This PR:
- Changes default interface from result of function passed via parameter pointer to result returned by function directly by its return value. 
- Adds support for epsilon. Epsilon is the maximal value of symobl data type. It also add back() to OrdVector to enable accesing epsilon transitions faster
What is not included:
-  I did not move the functions returning results via parameter pointer to a special file. Actually, I didn't notice that this was approved on the last meeting and I don't think it is a clear solution. We would need to use friend function or create some kind of helping structure. I think neither one of the options is worth tradeoff for increasing entropy by creating new file. Moreover, any mediocre C++ programmer will understand why there are different signatures …
=> Change interface and add epsilon

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_alphabets.py, bindings/python/tests/test_nfa.py, examples/example-jupyter.ipynb, include/mata/nfa.hh, src/afa/afa.cc, src/nfa/nfa-incl.cc, src/nfa/nfa.cc, src/nfa/noodlify.cc, src/nfa/tests-nfa.cc, src/tests-re2parser.cc
This PR unifies all alphabets into a single alphabet `OnTheFlyAlphabet`. Further, the PR includes updates to functions using alphabets to reflect introduced changes.
This PR covers the basic unification of alphabets as agreed upon in the last meeting. Additional modifications to alphabets which were suggested in the meeting will be added gradually when the wrapper is removed. 
Merging this PR allows us to remove `NfaWrapper` as proposed in #55.
=> Unify alphabets

.github/workflows/release.yml
This is another attempt with fixxing issues with merging public fork, which does not have permissions properly propagated.
=> Hotfix issues with release action

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_alphabets.py, include/mata/nfa.hh, src/CMakeLists.txt, src/nfa/nfa-universal.cc, src/nfa/nfa.cc, src/nfa/tests-nfa.cc
This PR removes `NfaWrapper` and moves its content to `Nfa` struct as discussed in meetings and in #53 and #55.
As of now, the following changes were introduced:
1. `NfaWrapper` is deleted.
2. Alphabet is now a member variable of `Nfa` struct, passed as a pointer to allow sharing alphabets.
3. Introduces basic key-value store for state dictionary and additional attributes the user might want to store together with the NFA.
4. State dictionary currently does not have any default implementation and will be implemented only when we have a need for it and know precisely how we need the state dictionary to behave.
5. Python binding has been reworked to reflect the above-mentioned changes. Particularly, how to work with the new alphabets.   
This PR resolves #53 and #55 can be safely closed.
1. …
=> Remove NfaWrapper

bindings/python/mata.pxd, bindings/python/mata.pyx, bindings/python/tests/test_nfa.py, examples/example04-complement.cc, include/mata/nfa.hh, src/nfa/nfa-concatenation.cc, src/nfa/nfa-incl.cc, src/nfa/nfa-intersection.cc, src/nfa/noodlify.cc, src/nfa/tests-nfa-concatenation.cc, src/nfa/tests-nfa-intersection.cc
As per request, this PR refactors algorithms for intersection and concatenation. As agreed upon, I have removed the introduced abstractions of these algorithms, moved all implementation code into a single function wherever possible, removed the corresponding classes and modified how we handle epsilon symbols in these algorithms.
Now, we support only the default epsilon symbol to be used as the epsilon symbol for these algorithms. It was decided that the other operations than the previously mentioned algorithms (specially designed to consider epsilon transitions) will ignore epsilon symbols whatsoever and compute with the default epsilon symbol as if it was a normal alphabet symbol instead, at least for now.
=> Rewrite automata algorithms with epsilons

include/mata/afa.hh, include/mata/closed_set.hh, src/afa/afa.cc, src/afa/tests-afa.cc
I've changed the former data structure for alternating automata, I've added structures for transition and inverse transition and several functions which enable us to inspect an alternating automaton using antichains (pre, post). I've also implemented two antichain-based AFA emptiness tests (which work in a forward and backward fashion).
I've also added a file closed_set.hh which makes the work with antichains easier.
I've also added several test cases.
=> AFA data structures, Closed set data structures, functions for inspecting an AFA, two AFA emptiness tests

include/mata/mintermization.hh, src/mintermization.cc, src/tests-mintermization.cc
This PR extends mintermization of NFA and AFA by adding option to mintermize multiple automata at the same time where resulting automata use the same minterms.
=> Mintermization of multiple automata

include/mata/inter-aut.hh, src/inter-aut.cc, src/nfa/nfa.cc, src/nfa/tests-nfa.cc, src/tests-parser.cc
This PR implements conversion of final states defined as conjunction of negations to set of final states. This is a case of explicit NFA created by mintermization from bitvector NFA where final states where defined by such formula.
=> added support for converting final states in conjunction of negations
